// port-lint: source lib.rs
package io.github.kotlinmania.schemars

/**
 * A type which can be described as a JSON Schema document.
 *
 * This is implemented for many Kotlin standard-library types and can be implemented manually for
 *
 * automatically; in Kotlin those are written by hand or generated by build tooling, with the
 * implementing object exposing all four trait functions.
 *
 * # Examples
 * Manual implementation:
 * ```
 * import io.github.kotlinmania.schemars.JsonSchema
 * import io.github.kotlinmania.schemars.Schema
 * import io.github.kotlinmania.schemars.SchemaGenerator
 * import io.github.kotlinmania.schemars.jsonSchema
 *
 * object NonGenericType : JsonSchema {
 *     override fun schemaName(): String = "NonGenericType"
 *     override fun schemaId(): String = "io.github.kotlinmania.NonGenericType"
 *     override fun jsonSchema(generator: SchemaGenerator): Schema = jsonSchema {
 *         "foo" to "bar"
 *     }
 * }
 * ```
 *
 * For generic types, the generated name and id should usually include the type parameter:
 * ```
 * class GenericTypeJsonSchema(private val inner: JsonSchema) : JsonSchema {
 *     override fun schemaName(): String = "GenericType_${'$'}{inner.schemaName()}"
 *     override fun schemaId(): String = "io.github.kotlinmania.GenericType<${'$'}{inner.schemaId()}>"
 *     override fun jsonSchema(generator: SchemaGenerator): Schema = jsonSchema {
 *         "foo" to "bar"
 *     }
 * }
 * ```
 */
interface JsonSchema {
    /**
     * Whether JSON Schemas generated for this type should be included directly in parent schemas,
     * rather than being re-used where possible using the `${'$'}ref` keyword.
     *
     * For trivial types (such as primitives), this should return `true`. For more complex types,
     * it should return `false`. For recursive types, this **must** return `false` to prevent
     * infinite cycles when generating schemas.
     *
     * By default, this returns `false`.
     */
    fun inlineSchema(): Boolean = false

    /**
     * The name of the generated JSON Schema.
     *
     * This is used as the title for root schemas, and the key within the root's `definitions`
     * property for subschemas.
     */
    fun schemaName(): String

    /**
     * Returns a string that uniquely identifies the schema produced by this type.
     *
     * This does not have to be a human-readable string, and the value will not itself be included
     * in generated schemas. If two types produce different schemas, then they **must** have
     * different [schemaId]s, but two types that produce identical schemas should *ideally* have
     * the same [schemaId].
     *
     * The default implementation returns the same value as [schemaName].
     */
    fun schemaId(): String = schemaName()

    /**
     * Generates a JSON Schema for this type.
     *
     * If the returned schema depends on any non-inlined (see [inlineSchema]) schemas, then this
     * method will add them to the [SchemaGenerator]'s schema definitions.
     *
     * This should not return a `${'$'}ref` schema.
     */
    fun jsonSchema(generator: SchemaGenerator): Schema

    fun schemarsPrivateNonOptionalJsonSchema(generator: SchemaGenerator): Schema =
        jsonSchema(generator)

    fun schemarsPrivateIsOption(): Boolean = false
}
